import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"
[window]
decorations = "None"
startup_mode = "FullScreen"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "Iosevka Bold Italic Nerd Font"

[font.italic]
family = "Iosevka Medium Italic Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.padding]
x = 10
y = 10


