os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} {{filename}}"
gui:
  showIcons: true
  showFileTree: true
  theme:
    activeBorderColor:
      - '#8bd5ca'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8bd5ca'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    '*': '#b7bdf8'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
