oS:
  openCommand: nvim {{filename}}
gui:
  returnImmediately: true
  theme:
    activeBorderColor:
      - '#8bd5ca'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    optionsTextColor:
      - '#cad3f5'
